import re

# SCONSTRUCT REGEX
VERSION_KEYWORD = 'Version'
MAJOR_KEYWORD   = 'major'
MINOR_KEYWORD   = 'minor'
POINT_KEYWORD   = 'point'
PATCH_KEYWORD   = 'patch'

IGNORE_WHITESPACES    = r'\s*'
ONE_OR_MORE_DIGITS    = r'\d+'

MATCH_MAJOR = rf"{IGNORE_WHITESPACES}{MAJOR_KEYWORD}{IGNORE_WHITESPACES}={IGNORE_WHITESPACES}{ONE_OR_MORE_DIGITS}{IGNORE_WHITESPACES},"
MATCH_MINOR = rf"{IGNORE_WHITESPACES}{MINOR_KEYWORD}{IGNORE_WHITESPACES}={IGNORE_WHITESPACES}{ONE_OR_MORE_DIGITS}{IGNORE_WHITESPACES},"
MATCH_POINT = rf"{IGNORE_WHITESPACES}{POINT_KEYWORD}{IGNORE_WHITESPACES}={IGNORE_WHITESPACES}{ONE_OR_MORE_DIGITS}{IGNORE_WHITESPACES},"
MATCH_PATCH = rf"{IGNORE_WHITESPACES}{PATCH_KEYWORD}{IGNORE_WHITESPACES}={IGNORE_WHITESPACES}{ONE_OR_MORE_DIGITS}{IGNORE_WHITESPACES},?{IGNORE_WHITESPACES}"

RE_PATTERN_SCONSTRUCT_VERSION = re.compile(
    rf"""
    (
    {VERSION_KEYWORD} \s*
    \(
        \s*
        {MATCH_MAJOR}
        \s*
        {MATCH_MINOR}
        \s*
        {MATCH_POINT}
        \s*
        {MATCH_PATCH}
        \s*
    \)
    )
    """,
    re.VERBOSE | re.IGNORECASE
)

POINT_PATTERN = rf"{POINT_KEYWORD}{IGNORE_WHITESPACES}={IGNORE_WHITESPACES}{ONE_OR_MORE_DIGITS}"

# VERSION REGEX
VERSION_FILE_POINT_PREFIX = rf'ADLMSDK_VERSION_POINT{IGNORE_WHITESPACES}={IGNORE_WHITESPACES}'

VERSION_FILE_POINT_PATTERN = re.compile(
    rf"""
    (
        {VERSION_FILE_POINT_PREFIX}
        {ONE_OR_MORE_DIGITS}
    )
    """,
    re.VERBOSE | re.IGNORECASE
)
